services:

# If in prod, if is developing, is better just use npm run start:dev
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: system-bank-back
  #   environment:
  #     DB_TYPE: postgres
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_DATABASE: ${DB_DATABASE}
  #     DB_SCHEMA: ${DB_SCHEMA}
  #     DATABASE_URL: ${DATABASE_URL}
  #     PORT: ${PORT}
  #     ENVIRONMENT: ${ENVIRONMENT}
  #     JWT_SECRET: ${JWT_SECRET}
  #   ports:
  #     - '${PORT}:${PORT}'
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network
      
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
