services:

# If is just developing, is better just use npm run `start:dev`. Comment if is developing
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: system-bank-back
  #   environment:
  #     DB_TYPE: postgres
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_DATABASE: ${DB_DATABASE}
  #     DB_SCHEMA: ${DB_SCHEMA}
  #     DATABASE_URL: ${DATABASE_URL}
  #     PORT: ${PORT}
  #     ENVIRONMENT: ${ENVIRONMENT}
  #     JWT_SECRET: ${JWT_SECRET}
  #   ports:
  #     - '${PORT}:${PORT}'
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app
  #   networks:
  #     - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # DinamicDNS
  # duckdns:
  #   image: lscr.io/linuxserver/duckdns:latest
  #   container_name: duckdns
  #   network_mode: host
  #   environment:
  #     - PUID=1000 
  #     - PGID=1000 
  #     - TZ=Etc/UTC
  #     - SUBDOMAINS=c86fa61a-af0e-46ce-8694-28e5b1bb9731 
  #     - TOKEN=a34bd75e-d67b-46b5-b95f-dbbed8fcd8f1 
  #     - UPDATE_IP=ipv4
  #     - LOG_FILE=false 
  #   volumes:
  #     - /caminho/para/duckdns/config:/config
  #   restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
